# Generated by Django 2.2.5 on 2019-09-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.ManyToManyField(to='beer.Tag'),
        ),
    ]
