# Generated by Django 2.2.5 on 2019-10-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_food_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairing',
            name='approved',
        ),
        migrations.AddField(
            model_name='beer',
            name='pairings',
            field=models.ManyToManyField(through='beer.Pairing', to='beer.Food'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='tags',
            field=models.ManyToManyField(to='beer.Tag'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
