# Generated by Django 2.2.5 on 2019-10-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0003_auto_20191014_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='limited_release',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='season',
            field=models.CharField(blank=True, choices=[('SP', 'Spring'), ('SU', 'Summer'), ('FA', 'Fall'), ('WI', 'Winter')], max_length=2),
        ),
        migrations.AddField(
            model_name='beer',
            name='seasonal_release',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
